#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";

# Start commands for application
require Mojolicious::Commands;
require App::WebSNMP;
my $commands = Mojolicious::Commands->new(app => App::WebSNMP->new);
push @{$commands->namespaces}, 'App::WebSNMP::Command';
$commands->run(@ARGV);
